### ISSUE TITLE
white screen on floorplan on fire 7

### ISSUE THREAD

**Issue by claudius61** [haynieresearch/jarvis#3]
I took as a starting point your site: floorplan on PC with firefox, it is ok but with fire 7 I have a white screen!
Do you have an idea on this problem?
thank you in advance.

**Comment by lancehaynie** [comment]
I have the same problem with my iPad, still working to resolve it. This part of my implementation was developed by @CCOSTAN. Maybe he has an idea as to why it does not work on some tablet devices.

**Comment by lancehaynie** [comment]
I made a mistake, HA-Floorplan is developed by @pkozul;  @CCOSTAN was just my inspiration for my project.

**Comment by CCOSTAN** [comment]
Unfortunately, this project is kind of abandoned. :(  I am in the process of transitioning completely over to Lovelace.  LoveLace is pretty powerful at the moment. 
https://github.com/CCOSTAN/Home-AssistantConfig/issues/565

**Comment by lancehaynie** [comment]
Agreed with @CCOSTAN, I am transitioning to Lovelace as well and appears to be very powerful.
