### ISSUE TITLE
stt error

### ISSUE THREAD

**Issue by hmmkash** [haynieresearch/jarvis#4]
I've got this error with stt
any idea ?
Thanks
Jarvis Speech to Text Engine
Haynie Research & Development LLC

WARNING:core.application:language not specified in profile, using 'en-US'
INFO:core.application:audio_engine not specified in profile, using defaults.
WARNING:core.application:stt_engine not specified in profile, using defaults.
WARNING:core.application:tts_engine not specified in profile, usingdefaults.
INFO:core.application:Using wake word 'Jarvis'
WARNING:core.application:input_device not specified in profile, defaulting to 'default' (Possible values: default, dmix-card-camerab409241-dev-0, dsnoop-card-camerab409241-dev-0, front-card-camerab409241-dev-0, hw-card-camerab409241-dev-0, iec958-card-camerab409241-dev-0, null, plughw-card-camerab409241-dev-0, surround21-card-camerab409241-dev-0, surround40-card-camerab409241-dev-0, surround41-card-camerab409241-dev-0, surround50-card-camerab409241-dev-0, surround51-card-camerab409241-dev-0, surround71-card-camerab409241-dev-0, sysdefault-card-camerab409241)
WARNING:core.application:output_device not specified in profile, defaulting to 'default' (Possible values: default, dmix-card-alsa-dev-0, dmix-card-alsa-dev-1, dsnoop-card-alsa-dev-0, dsnoop-card-alsa-dev-1, hw-card-alsa-dev-0, hw-card-alsa-dev-1, null, plughw-card-alsa-dev-0, plughw-card-alsa-dev-1, sysdefault-card-alsa)
INFO:core.mic:Waiting for keyword 'Jarvis'...
Traceback (most recent call last):
  File "/opt/jarvis/stt/stt.py", line 26, in <module>
    core.main()
  File "/opt/jarvis/stt/core/__main__.py", line 74, in main
    app.run()
  File "/opt/jarvis/stt/core/application.py", line 273, in run
    self.conversation.handleForever()
  File "/opt/jarvis/stt/core/conversation.py", line 58, in handleForever
    input = self.mic.listen()
  File "/opt/jarvis/stt/core/mic.py", line 223, in listen
    self.wait_for_keyword(self._keyword)
  File "/opt/jarvis/stt/core/mic.py", line 183, in wait_for_keyword
    self._input_rate):
  File "/opt/jarvis/stt/plugins/audioengine/defaultaudio/defaultaudio.py", line 144, in record
    output=False) as stream:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/jarvis/stt/plugins/audioengine/defaultaudio/defaultaudio.py", line 127, in open_stream
    device='default')
alsaaudio.ALSAAudioError: No such file or directory [default]

**Comment by lancehaynie** [comment]
Better late than never right? The STT errors are caused by the system not recognizing the default audio device.  Run aplay -l on your device and see what your playback device is. Then open up resources/asoundrc and modify it to your device and then copy it to ~/.asoundrc and it should fix the problem.
